clearer assert messages/structure in add_archive_file

diff --git a/.github/actions/add_archive_file/action.yml b/.github/actions/add_archive_file/action.yml
--- a/.github/actions/add_archive_file/action.yml
+++ b/.github/actions/add_archive_file/action.yml
@@ -195,7 +195,11 @@ runs:
       # Add the file
 
       echo "Adding to tar archive ${tar_archive} (displaying destination paths below)..."
-      sed_expression="${sed_expression}x"
+      sed_expression="${sed_expression}x" # x indicates we are using an extended regular expression
+      # Note: tar --append does not remove an existing file with the same name.
+      # However, in a tar archive where multiple file records share one path,
+      # the file closest to the end of the tar archive stream (i.e. the one we append)
+      # takes precedent over the earlier ones.
       tar --append -vf $tar_archive --transform "${sed_expression}" "$source_file" --show-transformed-names
       echo "Done"
 
@@ -226,7 +230,7 @@ runs:
       echo "Note: if archive is gzipped, size increase of archive may be smaller than size of added file."
       final_archive_size_1K="$(du --block-size=1K --apparent-size $archive_path | cut -f1)"
       echo "Size of original archive: ${original_archive_size_1K} K"
-      echo "Size of added file: ${expected_size_increase_1K} K"
+      echo "Size of added file: ${additions_size_1K} K"
       echo "New archive size: ${final_archive_size_1K} K"
 
       if [[ "$final_archive_size_1K" -le "$original_archive_size_1K" ]]; then
@@ -249,7 +253,7 @@ runs:
         echo "Success"
       fi
 
-      # Assert that we added a file
+      # Assert that we added the right number of files
       echo "Checking what files we added to the archive..."
       path_new_archive_contents="$RUNNER_TEMP/new_archive_contents.txt"
       if [[ $output_is_gzipped == 'true' ]]; then
@@ -260,33 +264,42 @@ runs:
       differences_path="$RUNNER_TEMP/archive_contents_difference.txt"
       echo "old archive contents <> new archive contents"
       diff $path_to_original_archive_contents $path_new_archive_contents | tee $differences_path
-      differences_count="$(cat $differences_path | grep ^[^0-9-] | wc -l)"
+      differences_count="$(cat "$differences_path" | grep '^[^0-9-]' | wc -l)"
+      echo "New archive has $differences_count added/removed filenames compared to original archive."
       if [[ differences_count != '1' ]]; then
-        echo "Assertion failed: expected 1 difference in file contents, but new archive has $differences_count added/removed filenames compared to original archive" >&2
+        echo "Assertion failed: expected 1 difference in file contents." >&2
         exit 1
       fi
-      readarray new_files_array < <(cat $differences_path | grep '^> ' | sed 's/^> //')
+
+      # Assert that the files we added are pretty much the estimated size
+      readarray new_files_array < <(cat "$differences_path" | grep '^> ' | sed 's/^> //')
+      new_files_total_uncompressed_1K='0'
       for item in "${new_files_array[@]}"; do
-        uncompressed_item_size_bytes="$(echo $item | awk '{print $3}')"
-        uncompressed_item_size_1K=$(( ( $uncompressed_item_size_bytes / 1024 ) + 1 )) # du rounds up, so we do the same
-        uncompressed_item_size_off_by_1K=$(( $uncompressed_item_size_1K - $expected_size_increase_1K - 1 ))
-        uncompressed_item_size_off_by_1K=${uncompressed_item_size_off_by_1K#-}      # absolute value
-        if [[ "$uncompressed_item_size_bytes" -eq '0' ]]; then
+        echo "File in new archive: $item"
+
+        # running total using var new_files_total_uncompressed_1K
+        item_uncompressed_size_bytes="$(echo $item | awk '{print $3}')"
+        item_uncompressed_size_1K=$(( $item_uncompressed_size_bytes + ( 1024 / 2 ) ) / 1024 )) # du rounds up, so we do the same
+        new_files_total_uncompressed_1K=$(( $new_files_total_uncompressed_1K + $item_uncompressed_size_bytes ))
+
+        # also check this file's individual size is not 0
+        if [[ "$item_uncompressed_size_bytes" -eq '0' ]]; then
           echo "Assertion failed: new item in archive is size 0." >&2
-          echo "Item: $item" >&2
-          exit 1
-        elif [[ "$uncompressed_item_size_off_by_1K" -gt $(( $expected_size_increase_1K / 4 )) ]]; then
-          echo "Assertion failed: size of archive additions (uncompressed size) differs by those files' original size by: $uncompressed_item_size_off_by_1K K" >&2
-          echo "Item: $item" >&2
           exit 1
         fi
       done
+      new_files_off_by_1K=$(( $new_files_total_uncompressed_1K - $additions_size_1K ))
+      new_files_off_by_1K=${new_files_off_by_1K#-}            # absolute value
+      if [[ "$new_files_off_by_1K" -gt $(( $additions_size_1K / 4 )) ]]; then
+        echo "Assertion failed: size (in archive) of uncompressed additions differs by those files' original size by: $new_files_off_by_1K K" >&2
+        exit 1
+      fi
       echo "Success"
     env:
       output_is_gzipped: ${{ inputs.is-gzip-compressed }}
       path_to_original_archive_contents: ${{ steps.pre-assert.outputs.archive_contents_record }}
       # make sure these were calculated with --block-size=1K.
       original_archive_size_1K: ${{ steps.pre-assert.outputs.archive_size }}
-      expected_size_increase_1K: ${{ steps.pre-assert.outputs.additions_size }}
+      additions_size_1K: ${{ steps.pre-assert.outputs.additions_size }}
       # make sure this matches the expression which defines the action's output.
       archive_path: ${{ inputs.archive-path }}
