changes

diff --git a/.github/actions/add_archive_file/action.yml b/.github/actions/add_archive_file/action.yml
--- a/.github/actions/add_archive_file/action.yml
+++ b/.github/actions/add_archive_file/action.yml
@@ -31,11 +31,11 @@ runs:
       ## Collect some info now so we can perform asserts at the end
 
       # calculate archive_size
-      archive_size="$(du --block-size=1K $archive_path | cut -f1)"
+      archive_size="$(du --block-size=1K --apparent-size $archive_path | cut -f1)"
       echo "archive_size=$archive_size" | tee -a $GITHUB_OUTPUT
 
       # calculate additions_size
-      additions_size="$(du --block-size=1K $file_additions | cut -f1)"
+      additions_size="$(du --block-size=1K --apparent-size $file_additions | cut -f1)"
       echo "additions_size=$additions_size" | tee -a $GITHUB_OUTPUT
 
       # calculate archive_contents
@@ -224,16 +224,14 @@ runs:
       
       # Assert that we changed the size of our archive
       echo "Note: if archive is gzipped, size increase of archive may be smaller than size of added file."
-      final_archive_size_1K="$(du --block-size=1K $archive_path | cut -f1)"
+      final_archive_size_1K="$(du --block-size=1K --apparent-size $archive_path | cut -f1)"
       echo "Size of original archive: ${original_archive_size_1K} K"
       echo "Size of added file: ${expected_size_increase_1K} K"
       echo "New archive size: ${final_archive_size_1K} K"
 
       if [[ "$final_archive_size_1K" -le "$original_archive_size_1K" ]]; then
         echo "Assertion failed: new archive is not larger than old archive" >&2
-        max_shrink="$((1024 * 30))" #30MB
-        actual_shrink="$(($original_archive_size_1K - $final_archive_size_1K))"
-        if [[ "$actual_shrink" -lt "$max_shrink"]]; then
+        if [[ "$output_is_gzipped" == 'true' ]]; then
           echo "Not failing, because difference in size could be explained by compression"
         else
           exit 1
@@ -255,7 +253,7 @@ runs:
       echo "Checking what files we added to the archive..."
       path_new_archive_contents="$RUNNER_TEMP/new_archive_contents.txt"
       if [[ $output_is_gzipped == 'true' ]]; then
-        tar -v -tz -f $archive_path > $path_new_archive_contents
+        tar -v -tzf $archive_path > $path_new_archive_contents
       else
         tar -v -tf $archive_path > $path_new_archive_contents
       fi
@@ -267,10 +265,18 @@ runs:
         echo "Assertion failed: expected 1 difference in file contents, but new archive has $differences_count added/removed filenames compared to original archive" >&2
         exit 1
       fi
-      readarray new_files_array <(cat $differences_path | grep '> ' | sed 's/^> //')
+      readarray new_files_array < <(cat $differences_path | grep '^> ' | sed 's/^> //')
       for item in "${new_files_array[@]}"; do
-        if [[ "$(echo $item > awk '{print $3}')" -eq '0' ]]; then
+        uncompressed_item_size_bytes="$(echo $item | awk '{print $3}')"
+        uncompressed_item_size_1K=$(( ( $uncompressed_item_size_bytes / 1024 ) + 1 )) # du rounds up, so we do the same
+        uncompressed_item_size_off_by_1K=$(( $uncompressed_item_size_1K - $expected_size_increase_1K - 1 ))
+        uncompressed_item_size_off_by_1K=${uncompressed_item_size_off_by_1K#-}      # absolute value
+        if [[ "$uncompressed_item_size_bytes" -eq '0' ]]; then
           echo "Assertion failed: new item in archive is size 0." >&2
+          echo "Item: $item" >&2
+          exit 1
+        elif [[ "$uncompressed_item_size_off_by_1K" -gt $(( $expected_size_increase_1K / 4 )) ]]; then
+          echo "Assertion failed: size of archive additions (uncompressed size) differs by those files' original size by: $uncompressed_item_size_off_by_1K K" >&2
           echo "Item: $item" >&2
           exit 1
         fi
