assert with actual tar list of files

diff --git a/.github/actions/add_archive_file/action.yml b/.github/actions/add_archive_file/action.yml
--- a/.github/actions/add_archive_file/action.yml
+++ b/.github/actions/add_archive_file/action.yml
@@ -37,12 +37,23 @@ runs:
       # calculate additions_size
       additions_size="$(du --block-size=1K $file_additions | cut -f1)"
       echo "additions_size=$additions_size" | tee -a $GITHUB_OUTPUT
+
+      # calculate archive_contents
+      record_path="$RUNNER_TEMP/original_archive_contents.txt"
+      if [[ $input_is_gzipped == "true" ]]; then
+        tar -v -tzf $archive_path > "$record_path"
+      else
+        tar -v -tf $archive_path > "$record_path"
+      fi
+      echo "archive_contents_record=$record_path" | tee -a $GITHUB_OUTPUT
     env:
+      input_is_gzipped: ${{ inputs.is-gzip-compressed }}
       archive_path: ${{ inputs.archive-path }}
       file_additions: ${{ inputs.file-path }}
     # outputs:
     # archive_size: Size of original archive, divided by 1024 bytes, no K suffix.
     # additions_size: Total size of files to add, divided by 1024 bytes, no K suffix.
+    # archive_contents_record: Path to file containing output of tar -t (list of files in archive)
 
   - name: Make a working directory available, format input path (archive-hierarchy-location)
     id: safe-paths
@@ -199,7 +210,7 @@ runs:
     shell: bash
     run: |
       ## Rezip the archive, return to original location
-      cat $decompressed_path | gzip > $original_archive_path
+      cat $decompressed_path | gzip --best > $original_archive_path
     env:
       original_archive_path: ${{ inputs.archive-path }}
       decompressed_path: ${{ steps.unzip-archive.outputs.decompressed_path }}
@@ -218,9 +229,15 @@ runs:
       echo "Size of added file: ${expected_size_increase_1K} K"
       echo "New archive size: ${final_archive_size_1K} K"
 
-      if [ "$final_archive_size_1K" -le "$original_archive_size_1K" ]; then
+      if [[ "$final_archive_size_1K" -le "$original_archive_size_1K" ]]; then
         echo "Assertion failed: new archive is not larger than old archive" >&2
-        exit 1
+        max_shrink="$((1024 * 30))" #30MB
+        actual_shrink="$(($original_archive_size_1K - $final_archive_size_1K))"
+        if [[ "$actual_shrink" -lt "$max_shrink"]]; then
+          echo "Not failing, because difference in size could be explained by compression"
+        else
+          exit 1
+        fi
       fi
 
       # Assert that we created a valid archive
@@ -233,8 +250,35 @@ runs:
         tar -x --to-stdout -f $archive_path >> /dev/null
         echo "Success"
       fi
+
+      # Assert that we added a file
+      echo "Checking what files we added to the archive..."
+      path_new_archive_contents="$RUNNER_TEMP/new_archive_contents.txt"
+      if [[ $output_is_gzipped == 'true' ]]; then
+        tar -v -tz -f $archive_path > $path_new_archive_contents
+      else
+        tar -v -tf $archive_path > $path_new_archive_contents
+      fi
+      differences_path="$RUNNER_TEMP/archive_contents_difference.txt"
+      echo "old archive contents <> new archive contents"
+      diff $path_to_original_archive_contents $path_new_archive_contents | tee $differences_path
+      differences_count="$(cat $differences_path | grep ^[^0-9-] | wc -l)"
+      if [[ differences_count != '1' ]]; then
+        echo "Assertion failed: expected 1 difference in file contents, but new archive has $differences_count added/removed filenames compared to original archive" >&2
+        exit 1
+      fi
+      readarray new_files_array <(cat $differences_path | grep '> ' | sed 's/^> //')
+      for item in "${new_files_array[@]}"; do
+        if [[ "$(echo $item > awk '{print $3}')" -eq '0' ]]; then
+          echo "Assertion failed: new item in archive is size 0." >&2
+          echo "Item: $item" >&2
+          exit 1
+        fi
+      done
+      echo "Success"
     env:
       output_is_gzipped: ${{ inputs.is-gzip-compressed }}
+      path_to_original_archive_contents: ${{ steps.pre-assert.outputs.archive_contents_record }}
       # make sure these were calculated with --block-size=1K.
       original_archive_size_1K: ${{ steps.pre-assert.outputs.archive_size }}
       expected_size_increase_1K: ${{ steps.pre-assert.outputs.additions_size }}
